# Generated by Django 5.1.3 on 2024-11-10 23:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default_profile_ov49xh', max_length=255, verbose_name='image'),
        ),
    ]
