# Generated by Django 5.1.3 on 2024-11-11 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default_profile_ov49xh', upload_to='images/'),
        ),
    ]
