# Generated by Django 3.2.25 on 2024-12-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reference_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
