# Generated by Django 3.2.25 on 2024-12-15 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('notifications', '0003_notification_reference_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='reference_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='post_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='posts.post'),
        ),
    ]
