# Generated by Django 3.2.25 on 2024-12-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20241215_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow'), ('post_update', 'Post Update'), ('new_post', 'New Post')], default='post_update', max_length=20),
        ),
    ]
